### ISSUE TITLE
Grammar correction; delete after fix

### ISSUE THREAD

**Issue by bradley-r** [jackputtockk/animated-gradient#2]
readme.md should state something like "This work is licensed under the MIT License."

"Licensed under MIT" would suggest the institute itself is covering it, which is just a tad unlikely.

**Comment by jackputtockk** [comment]
Issue resolved. 

-----
Jack Puttock
<a href="https://www.jackputtock.com">jackputtock.com</a>
Front End Web Developer
CEO @ Arctane Group
