### ISSUE TITLE
Text Scaling

### ISSUE THREAD

**Issue by bradley-r** [jackputtockk/animated-gradient#6]
At 5K resolution, fullscreen or otherwise, credit text is displayed incorrectly.

![image](https://user-images.githubusercontent.com/43189454/63381211-25e54480-c390-11e9-80d0-607478e6a37d.png)

**Comment by jackputtockk** [comment]
@bradley-r Issue Resolved. 

-----
Jack Puttock
[jackputtock.com](https://www.arctanegroup.com)
Front End Web Developer
CEO at [Arctane Group](https://www.arctanegroup.com)
